name: Check markdown as reusable workflow
on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
jobs:
  check-section:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set directory
        env:
          DIR: ${{inputs.dir}}
        run: |
          echo "DIRECTORY=${DIR}" >> $GITHUB_ENV
        shell: bash

      - name: call linter action
        id: call-linter
        uses: ./.github/actions/lab40
        with:
          dir: ${{inputs.dir}}

      - name: Format result
        id: format-result
        uses: actions/github-script@v7
        with:
          github-token: $GITHUB_TOKEN
          result-encoding: string
          script: |
            const output = `#### Lint 📖
            <details>
            \`\`\`
            ${{ steps.lint.output.report }}
            \`\`\`
            </details>`
            return output;

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: ${{ inputs.dir }}

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ${{ inputs.dir }}
            ${{ steps.format-result.outputs.result }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## ${{ inputs.dir }}
            ${{ steps.format-result.outputs.result }}
          edit-mode: replace